### ISSUE TITLE
Outside the local network

### ISSUE THREAD

**Issue by LyonelB** [quiniouben/vban#9]
Would it be wonderful to be able to use vban outside the local network?
Like OpenOb : https://jamesharrison.github.io/openob/

**Comment by quiniouben** [comment]
Hello. To use some audio outside local network, you probably want to use some dedicated codec.
Currently, vban_receptor only proposes PCM support because VBAN specifications and other implementations do so. Don't hesitate to follow [vban homepage](http://vb-audio.pagesperso-orange.fr/Voicemeeter/vban.htm) to see if specifications change. If there is some support of dedicated codec(s), and they are compatible with open source licensing, this project could implement its support.

**Comment by quiniouben** [comment]
See [this post](https://forum.vb-audio.com/viewtopic.php?f=9&t=479&sid=745c95e41fdb682e0f820857d3ccdf9d]) in vb-audio forum on this topic
